// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFk8vc5c0n3DvlcJ3J0Jrz0PYjmxFZ5So',
    appId: '1:488926667242:web:2a8303f18248e65d36d293',
    messagingSenderId: '488926667242',
    projectId: 'asset-audit-95195',
    authDomain: 'asset-audit-95195.firebaseapp.com',
    storageBucket: 'asset-audit-95195.firebasestorage.app',
    measurementId: 'G-TK574XGP83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCJr5pI1lSw4ZNKTLHEBuyeqgLCx8nmo',
    appId: '1:488926667242:android:f88ff89904a8d9be36d293',
    messagingSenderId: '488926667242',
    projectId: 'asset-audit-95195',
    storageBucket: 'asset-audit-95195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1aOLhKdptkthsr-Su7KvNs_gb_cOUwBM',
    appId: '1:488926667242:ios:e9d4a13a3673601236d293',
    messagingSenderId: '488926667242',
    projectId: 'asset-audit-95195',
    storageBucket: 'asset-audit-95195.firebasestorage.app',
    iosClientId:
        '488926667242-e7v8hmvb7j1o5rpos7tpqrpoclfipqhj.apps.googleusercontent.com',
    iosBundleId: 'com.irpc.assetApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1aOLhKdptkthsr-Su7KvNs_gb_cOUwBM',
    appId: '1:488926667242:ios:e9d4a13a3673601236d293',
    messagingSenderId: '488926667242',
    projectId: 'asset-audit-95195',
    storageBucket: 'asset-audit-95195.firebasestorage.app',
    iosClientId:
        '488926667242-e7v8hmvb7j1o5rpos7tpqrpoclfipqhj.apps.googleusercontent.com',
    iosBundleId: 'com.irpc.assetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFk8vc5c0n3DvlcJ3J0Jrz0PYjmxFZ5So',
    appId: '1:488926667242:web:85a4cd3ae5456a3536d293',
    messagingSenderId: '488926667242',
    projectId: 'asset-audit-95195',
    authDomain: 'asset-audit-95195.firebaseapp.com',
    storageBucket: 'asset-audit-95195.firebasestorage.app',
    measurementId: 'G-EL0ZEK1W6Z',
  );
}
